config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get  'pages/home'
  get 'about',to: 'pages#about'
  resources :articles ,only:[:show, :index, :create, :new, :edit, :update, :destroy]
  get 'signup', to: 'users#new'
  # post 'users', to: 'users#create'
  resources :users, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: {minimum: 6, maximum: 100}
  validates :description, presence: true, length:{minimum: 6, maximum:100} 
end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email = email.downcase}
  has_many :articles
  validates :username, presence: true, 
            uniqueness: { case_sensitive: false }, 
            length:{ minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
             uniqueness: { case_sensitive: false },
             length:{ maximum: 51 },
             format: { with:VALID_EMAIL_REGEX }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController 
  
  before_action :set_article, only: [:show, :update, :edit, :destroy]
 
 def show
   # @article= Article.find(params[:id])
  end

  def index
    @articles=Article.all
  end

  def new 
    @article=Article.new
  end

  def edit
  #@article= Article.find(params[:id])   
  end

  def create
  @article=Article.new(article_params)#params.require(:article).permit(:title, :description))
  # render plain: @article.inspect 
  @article.user = User.first
  if @article.save
    flash[:notice] = "Article was save successfully"
      redirect_to @article
   else
    render 'new'
   end
  end
  
  def update
    #@article = Article.find(params[:id])
   if  @article.update(article_params)#params.require(:article).permit(:title, :description))
       flash[:notice] = "Article was update successfully"
      redirect_to @article
   else
    render 'edit'
   end
  end

  def destroy
    #@article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path 
  end
 
private 

def set_article
  @article = Article.find(params[:id])
end

def article_params
  params.require(:article).permit(:title, :description)
end




end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def new 
@user = User.new
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<div class="container">
 <div class="row justify-content-center">
   <div class="col-10">
   <%= render 'shared/errors' , obj: @article%>
        <%= form_with(model: @article, class:"shadow p-3 mb-3 bg-info rounded", local: true)  do |f|%>
         <div class="form-group row">
            <%= f.label :Title, class:"col-2 col-form-level text-light"%>
            <div class="col-10">
              <%= f.text_field :title, class:"form-control shadow rounded", placeholder:"Title of Article"%>
            </div>
        </div> 
        <div class="form-group row">
            <%= f.label :Description, class:"col-2 col-form-level text-light"%>
           <div class="col-10">
            <%= f.text_area :description, rows:10, class:"form-control shadow rounded", placeholder:"Description of Article"%>
           </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit class:'btn btn-outline-light btn-lg'%>
        </div>
        <% end %>
     </div>
    <%= link_to '[ Cancel and Go to Article Listing Page ]', articles_path(@article.id), class:"text-info"%>
  </div>
</div>

app/views/articles/edit.html.erb
<h1>This Is Edit Article Page</h1>
<%= render 'form'%>

app/views/articles/index.html.erb
  <h1 class="text-center">This Is Articles Listing Index Page</h1>
  <div class="container">
  <% @articles.each do |article| %>
      <div class="row justify-content-md-center">
        <div class="col-10 mt-4 mb-4">
          <div class="card text-center">
              <div class="card-header font-italic">
                by <%= article.user.username if article.user%>
              </div>
              <div class="card-body">
                <h5 class="card-title"><%=link_to article.title, article_path(article.id), class:"text-success"%></h5>
                <p class="card-text"><%=truncate(article.description, length: 100)%></p>
                <%= link_to 'show', article_path(article.id), class:"btn btn-outline-success"%>
                <%= link_to 'edit', edit_article_path(article.id), class:"btn btn-outline-info"%>
                <%= link_to 'Delete', article_path(article.id), method: :delete ,data: {confirm:"Are You Sure ? , You Want To Delete"}, class:"btn btn-outline-danger"%>
              </div>
                <div class="card-footer text-muted">
                  <small>Created <%= time_ago_in_words(article.created_at) %> ago, edited <%= time_ago_in_words(article.updated_at)%> ago</small>
                </div>
            </div>
        </div>
      </div>
  <%end%>
  </div>





  <%
=begin%>
 <p><%= link_to 'Create New Article', new_article_path()%></p> 
<%
=end%>
  

app/views/articles/new.html.erb
<div id="page-content">
<h1 class="text-center">This Is Create New Article Page</h1>
 <%= render 'form'%>
 </div>



<%
=begin%>
 <%if @article.errors.any?%>
<h2>The Following message Prevant To Save</h2>
<ul>
<% @article.errors.full_messages.each do |msg|%>
<li><%= msg %></li>
<%end%>
</ul>
<%end%>
<%= form_with scope: :article, url: articles_path, local: true do |f|%>
   <p><%= f.label :Title %><br/>
      <%= f.text_field :title%>
   </p>
   <p><%= f.label :Description %><br/>
      <%= f.text_area :description%>
   </p>

   <p>
   <%= f.submit %>
   </p>
<% end %> 
<%
=end%>

app/views/articles/show.html.erb
  <h2 class="text-center mt-4"><%= @article.title  %></h2>
  <div class="container">
      <div class="row justify-content-md-center">
        <div class="col-10 mt-4">
          <div class="card text-center">
              <div class="card-header font-italic">
                by <%= @article.user.username if @article.user %>
              </div>
              <div class="card-body">
                <div class="card-text text-left"><%= simple_format(@article.description) %></div>
                <%= link_to 'edit', edit_article_path(@article), class:"btn btn-outline-info"%>
                <%= link_to 'Delete', article_path(@article), method: :delete ,data: {confirm:"Are You Sure ? , You Want To Delete"}, class:"btn btn-outline-danger"%>
              </div>
                <div class="card-footer text-muted">
                  <small>Created <%= time_ago_in_words(@article.created_at) %> ago, edited <%= time_ago_in_words(@article.updated_at)%> ago</small>
                </div>
            </div>
        </div>
      </div>
  </div>





  <%
=begin%>
 <p><%= link_to 'Create New Article', new_article_path()%></p> 
<%
=end%>
  

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; StoneAge Blog</small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg|%>
  <div class="container">
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= msg%>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
    </div>
  </div>
<%end%>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-white">
  <%= link_to 'StoneAge Blog', root_path, class:"navbar-brand",id:"logo"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent ">
    <ul class="navbar-nav mr-auto">
      <%
=begin%>
 <li class="nav-item active">
        <%= link_to 'Articles', articles_path, class:"nav-link"%>
      </li> 
<%
=end%>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Articles
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Create new article", new_article_path, class:"dropdown-item" %>
          <%= link_to "View articles", articles_path, class:"dropdown-item" %>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%=about_path%>">About</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>R3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body class="d-flex flex-column">
    <%= render 'layouts/navigation'%>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1 style="text-align:center"> This Is About Pages</h1>

app/views/pages/home.html.erb
  <div class="container p-5">
    <div class="jumbotron text-center text-white">
      <h1 class="display-4">StoneAge Blog</h1>
      <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
      <hr class="my-4">
      <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
      <a class="btn btn-success btn-lg" href="#" role="button">Sign Up!</a>
    </div>
  </div>
 

app/views/shared/_errors.html.erb
<%if obj.errors.any?%>

    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
       <span aria-hidden="true">&times;</span>
      </button>
      <h4 class="alert-heading">The Following Errors Prevant To Save!</h4>
      <ul>
      <% obj.errors.full_messages.each do |msg|%>
      <li><%= msg %></li>
      <%end%>
      </ul>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
       <span aria-hidden="true">&times;</span>
      </button>
    </div>

<%end%>
  

app/views/users/_form.html.erb
<div class="container">
 <div class="row justify-content-center">
   <div class="col-10">
   <%= render 'shared/errors' , obj: @user%>
        <%= form_with(model: @user, class:"shadow p-3 mb-3 bg-info rounded", local: true)  do |f|%>
         <div class="form-group row">
            <%= f.label :Username, class:"col-2 col-form-level text-light"%>
            <div class="col-10">
              <%= f.text_field :username, class:"form-control shadow rounded", placeholder:"Enter a Username"%>
            </div>
        </div> 
        <div class="form-group row">
            <%= f.label :email, class:"col-2 col-form-level text-light"%>
           <div class="col-10">
            <%= f.email_field :email, class:"form-control shadow rounded", placeholder:"Enter your Email"%>
           </div>
        </div>

        <div class="form-group row">
            <%= f.label :password, class:"col-2 col-form-level text-light"%>
           <div class="col-10">
            <%= f.password_field :password, class:"form-control shadow rounded", placeholder:"Enter your Password"%>
           </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit class:'btn btn-outline-light btn-lg'%>
        </div>
        <% end %>
     </div>
    <%= link_to '[ Cancel and Go to Article Listing Page ]', users_path(@user.id), class:"text-info"%>
  </div>
</div>

app/views/users/new.html.erb
<div id="page-content">
<h1 class="text-center">Sign up for Apha Blog</h1>
 <%= render 'form'%>
 </div>